name: My Workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Edgio
        uses: ronaldrpruitt/deploy-action@v1.0.8
        with:
          BRANCH_NAME: ${{ github.event.ref }}  # Pass the branch name as an input parameter
          EDGIO_DEPLOY_TOKEN: ${{ secrets.EDGIO_DEPLOY_TOKEN }}

