name: My Workflow
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Edgio
        uses: ronaldrpruitt/deploy-action@v1.0.3
        with:
          branch-name: 'master'
          edgio-deploy-token: ${{ secrets.EDGIO_DEPLOY_TOKEN }}
