# .github/workflows/deploy-to-edgio.yml

name: Deploy to Edgio

on:
  push:
    branches:
      - main
      - staging

env:
  DEPLOY_TOKEN: ${{ inputs.edgio_deploy_token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Deploy to Edgio
        uses: ronaldrpruitt/deploy-action@v1.0.8
        with:
          environment: ${{ github.event_name }}
          branch: ${{ github.ref }}
          deploy_token: ${{ env.DEPLOY_TOKEN }}


